// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBGROUPRELATIONUSERINFO_GROUPPACK_H_
#define FLATBUFFERS_GENERATED_FBGROUPRELATIONUSERINFO_GROUPPACK_H_

#include "flatbuffers/flatbuffers.h"

namespace grouppack {

struct T_GROUP_RELATION_USER_INFO;

struct T_GROUP_RELATION_USER_INFO FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_GROUP_ID = 4,
    VT_MESSAGE_STATUS = 6,
    VT_SAVE_TYPE = 8
  };
  uint64_t group_id() const { return GetField<uint64_t>(VT_GROUP_ID, 0); }
  int8_t message_status() const { return GetField<int8_t>(VT_MESSAGE_STATUS, 0); }
  int8_t save_type() const { return GetField<int8_t>(VT_SAVE_TYPE, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_GROUP_ID) &&
           VerifyField<int8_t>(verifier, VT_MESSAGE_STATUS) &&
           VerifyField<int8_t>(verifier, VT_SAVE_TYPE) &&
           verifier.EndTable();
  }
};

struct T_GROUP_RELATION_USER_INFOBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_group_id(uint64_t group_id) { fbb_.AddElement<uint64_t>(T_GROUP_RELATION_USER_INFO::VT_GROUP_ID, group_id, 0); }
  void add_message_status(int8_t message_status) { fbb_.AddElement<int8_t>(T_GROUP_RELATION_USER_INFO::VT_MESSAGE_STATUS, message_status, 0); }
  void add_save_type(int8_t save_type) { fbb_.AddElement<int8_t>(T_GROUP_RELATION_USER_INFO::VT_SAVE_TYPE, save_type, 0); }
  T_GROUP_RELATION_USER_INFOBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_GROUP_RELATION_USER_INFOBuilder &operator=(const T_GROUP_RELATION_USER_INFOBuilder &);
  flatbuffers::Offset<T_GROUP_RELATION_USER_INFO> Finish() {
    auto o = flatbuffers::Offset<T_GROUP_RELATION_USER_INFO>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<T_GROUP_RELATION_USER_INFO> CreateT_GROUP_RELATION_USER_INFO(flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t group_id = 0,
    int8_t message_status = 0,
    int8_t save_type = 0) {
  T_GROUP_RELATION_USER_INFOBuilder builder_(_fbb);
  builder_.add_group_id(group_id);
  builder_.add_save_type(save_type);
  builder_.add_message_status(message_status);
  return builder_.Finish();
}

inline const grouppack::T_GROUP_RELATION_USER_INFO *GetT_GROUP_RELATION_USER_INFO(const void *buf) {
  return flatbuffers::GetRoot<grouppack::T_GROUP_RELATION_USER_INFO>(buf);
}

inline bool VerifyT_GROUP_RELATION_USER_INFOBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<grouppack::T_GROUP_RELATION_USER_INFO>(nullptr);
}

inline void FinishT_GROUP_RELATION_USER_INFOBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<grouppack::T_GROUP_RELATION_USER_INFO> root) {
  fbb.Finish(root);
}

}  // namespace grouppack

#endif  // FLATBUFFERS_GENERATED_FBGROUPRELATIONUSERINFO_GROUPPACK_H_
