// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBGROUPCLIENTSENDMESSAGERS_GROUPPACK_H_
#define FLATBUFFERS_GENERATED_FBGROUPCLIENTSENDMESSAGERS_GROUPPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace grouppack {

struct T_GROUP_CLIENT_SEND_MESSAGE_RS;

struct T_GROUP_CLIENT_SEND_MESSAGE_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_MESSAGE_ID = 6,
    VT_GROUP_ID = 8,
    VT_S_MSG = 10
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t message_id() const { return GetField<uint64_t>(VT_MESSAGE_ID, 0); }
  uint64_t group_id() const { return GetField<uint64_t>(VT_GROUP_ID, 0); }
  const commonpack::S_MSG *s_msg() const { return GetPointer<const commonpack::S_MSG *>(VT_S_MSG); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_MESSAGE_ID) &&
           VerifyField<uint64_t>(verifier, VT_GROUP_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_S_MSG) &&
           verifier.VerifyTable(s_msg()) &&
           verifier.EndTable();
  }
};

struct T_GROUP_CLIENT_SEND_MESSAGE_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_GROUP_CLIENT_SEND_MESSAGE_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_message_id(uint64_t message_id) { fbb_.AddElement<uint64_t>(T_GROUP_CLIENT_SEND_MESSAGE_RS::VT_MESSAGE_ID, message_id, 0); }
  void add_group_id(uint64_t group_id) { fbb_.AddElement<uint64_t>(T_GROUP_CLIENT_SEND_MESSAGE_RS::VT_GROUP_ID, group_id, 0); }
  void add_s_msg(flatbuffers::Offset<commonpack::S_MSG> s_msg) { fbb_.AddOffset(T_GROUP_CLIENT_SEND_MESSAGE_RS::VT_S_MSG, s_msg); }
  T_GROUP_CLIENT_SEND_MESSAGE_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_GROUP_CLIENT_SEND_MESSAGE_RSBuilder &operator=(const T_GROUP_CLIENT_SEND_MESSAGE_RSBuilder &);
  flatbuffers::Offset<T_GROUP_CLIENT_SEND_MESSAGE_RS> Finish() {
    auto o = flatbuffers::Offset<T_GROUP_CLIENT_SEND_MESSAGE_RS>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<T_GROUP_CLIENT_SEND_MESSAGE_RS> CreateT_GROUP_CLIENT_SEND_MESSAGE_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t message_id = 0,
    uint64_t group_id = 0,
    flatbuffers::Offset<commonpack::S_MSG> s_msg = 0) {
  T_GROUP_CLIENT_SEND_MESSAGE_RSBuilder builder_(_fbb);
  builder_.add_group_id(group_id);
  builder_.add_message_id(message_id);
  builder_.add_s_msg(s_msg);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline const grouppack::T_GROUP_CLIENT_SEND_MESSAGE_RS *GetT_GROUP_CLIENT_SEND_MESSAGE_RS(const void *buf) {
  return flatbuffers::GetRoot<grouppack::T_GROUP_CLIENT_SEND_MESSAGE_RS>(buf);
}

inline bool VerifyT_GROUP_CLIENT_SEND_MESSAGE_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<grouppack::T_GROUP_CLIENT_SEND_MESSAGE_RS>(nullptr);
}

inline void FinishT_GROUP_CLIENT_SEND_MESSAGE_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<grouppack::T_GROUP_CLIENT_SEND_MESSAGE_RS> root) {
  fbb.Finish(root);
}

}  // namespace grouppack

#endif  // FLATBUFFERS_GENERATED_FBGROUPCLIENTSENDMESSAGERS_GROUPPACK_H_
