// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBGROUPGETOFFLINEMSGRS_GROUPPACK_H_
#define FLATBUFFERS_GENERATED_FBGROUPGETOFFLINEMSGRS_GROUPPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "fb_group_all_offline_msg_generated.h"
#include "fb_group_info_generated.h"
#include "fb_group_offline_msg_generated.h"

namespace grouppack {

struct T_GROUP_GET_OFFLINE_MESSAGE_RS;

struct T_GROUP_GET_OFFLINE_MESSAGE_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_LIST_GROUP_OFFLINE_MSG_RESPONSE = 6
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  const flatbuffers::Vector<flatbuffers::Offset<grouppack::T_GROUP_ALL_OFFLINE_MSG>> *list_group_offline_msg_response() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<grouppack::T_GROUP_ALL_OFFLINE_MSG>> *>(VT_LIST_GROUP_OFFLINE_MSG_RESPONSE); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_LIST_GROUP_OFFLINE_MSG_RESPONSE) &&
           verifier.Verify(list_group_offline_msg_response()) &&
           verifier.VerifyVectorOfTables(list_group_offline_msg_response()) &&
           verifier.EndTable();
  }
};

struct T_GROUP_GET_OFFLINE_MESSAGE_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_GROUP_GET_OFFLINE_MESSAGE_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_list_group_offline_msg_response(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<grouppack::T_GROUP_ALL_OFFLINE_MSG>>> list_group_offline_msg_response) { fbb_.AddOffset(T_GROUP_GET_OFFLINE_MESSAGE_RS::VT_LIST_GROUP_OFFLINE_MSG_RESPONSE, list_group_offline_msg_response); }
  T_GROUP_GET_OFFLINE_MESSAGE_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_GROUP_GET_OFFLINE_MESSAGE_RSBuilder &operator=(const T_GROUP_GET_OFFLINE_MESSAGE_RSBuilder &);
  flatbuffers::Offset<T_GROUP_GET_OFFLINE_MESSAGE_RS> Finish() {
    auto o = flatbuffers::Offset<T_GROUP_GET_OFFLINE_MESSAGE_RS>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_GROUP_GET_OFFLINE_MESSAGE_RS> CreateT_GROUP_GET_OFFLINE_MESSAGE_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<grouppack::T_GROUP_ALL_OFFLINE_MSG>>> list_group_offline_msg_response = 0) {
  T_GROUP_GET_OFFLINE_MESSAGE_RSBuilder builder_(_fbb);
  builder_.add_list_group_offline_msg_response(list_group_offline_msg_response);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_GROUP_GET_OFFLINE_MESSAGE_RS> CreateT_GROUP_GET_OFFLINE_MESSAGE_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    const std::vector<flatbuffers::Offset<grouppack::T_GROUP_ALL_OFFLINE_MSG>> *list_group_offline_msg_response = nullptr) {
  return CreateT_GROUP_GET_OFFLINE_MESSAGE_RS(_fbb, s_rs_head, list_group_offline_msg_response ? _fbb.CreateVector<flatbuffers::Offset<grouppack::T_GROUP_ALL_OFFLINE_MSG>>(*list_group_offline_msg_response) : 0);
}

inline const grouppack::T_GROUP_GET_OFFLINE_MESSAGE_RS *GetT_GROUP_GET_OFFLINE_MESSAGE_RS(const void *buf) {
  return flatbuffers::GetRoot<grouppack::T_GROUP_GET_OFFLINE_MESSAGE_RS>(buf);
}

inline bool VerifyT_GROUP_GET_OFFLINE_MESSAGE_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<grouppack::T_GROUP_GET_OFFLINE_MESSAGE_RS>(nullptr);
}

inline void FinishT_GROUP_GET_OFFLINE_MESSAGE_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<grouppack::T_GROUP_GET_OFFLINE_MESSAGE_RS> root) {
  fbb.Finish(root);
}

}  // namespace grouppack

#endif  // FLATBUFFERS_GENERATED_FBGROUPGETOFFLINEMSGRS_GROUPPACK_H_
