// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBGROUPTYPELISTRS_GROUPPACK_H_
#define FLATBUFFERS_GENERATED_FBGROUPTYPELISTRS_GROUPPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "fb_group_type_info_generated.h"

namespace grouppack {

struct T_GROUP_TYPE_LIST_RS;

struct T_GROUP_TYPE_LIST_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_LIST_GROUP_TYPE_INFO = 6
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  const flatbuffers::Vector<flatbuffers::Offset<grouppack::T_GROUP_TYPE_INFO>> *list_group_type_info() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<grouppack::T_GROUP_TYPE_INFO>> *>(VT_LIST_GROUP_TYPE_INFO); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_LIST_GROUP_TYPE_INFO) &&
           verifier.Verify(list_group_type_info()) &&
           verifier.VerifyVectorOfTables(list_group_type_info()) &&
           verifier.EndTable();
  }
};

struct T_GROUP_TYPE_LIST_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_GROUP_TYPE_LIST_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_list_group_type_info(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<grouppack::T_GROUP_TYPE_INFO>>> list_group_type_info) { fbb_.AddOffset(T_GROUP_TYPE_LIST_RS::VT_LIST_GROUP_TYPE_INFO, list_group_type_info); }
  T_GROUP_TYPE_LIST_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_GROUP_TYPE_LIST_RSBuilder &operator=(const T_GROUP_TYPE_LIST_RSBuilder &);
  flatbuffers::Offset<T_GROUP_TYPE_LIST_RS> Finish() {
    auto o = flatbuffers::Offset<T_GROUP_TYPE_LIST_RS>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_GROUP_TYPE_LIST_RS> CreateT_GROUP_TYPE_LIST_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<grouppack::T_GROUP_TYPE_INFO>>> list_group_type_info = 0) {
  T_GROUP_TYPE_LIST_RSBuilder builder_(_fbb);
  builder_.add_list_group_type_info(list_group_type_info);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_GROUP_TYPE_LIST_RS> CreateT_GROUP_TYPE_LIST_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    const std::vector<flatbuffers::Offset<grouppack::T_GROUP_TYPE_INFO>> *list_group_type_info = nullptr) {
  return CreateT_GROUP_TYPE_LIST_RS(_fbb, s_rs_head, list_group_type_info ? _fbb.CreateVector<flatbuffers::Offset<grouppack::T_GROUP_TYPE_INFO>>(*list_group_type_info) : 0);
}

inline const grouppack::T_GROUP_TYPE_LIST_RS *GetT_GROUP_TYPE_LIST_RS(const void *buf) {
  return flatbuffers::GetRoot<grouppack::T_GROUP_TYPE_LIST_RS>(buf);
}

inline bool VerifyT_GROUP_TYPE_LIST_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<grouppack::T_GROUP_TYPE_LIST_RS>(nullptr);
}

inline void FinishT_GROUP_TYPE_LIST_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<grouppack::T_GROUP_TYPE_LIST_RS> root) {
  fbb.Finish(root);
}

}  // namespace grouppack

#endif  // FLATBUFFERS_GENERATED_FBGROUPTYPELISTRS_GROUPPACK_H_
