// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBGROUPCREATERS_GROUPPACK_H_
#define FLATBUFFERS_GENERATED_FBGROUPCREATERS_GROUPPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "fb_group_info_generated.h"
#include "fb_group_offline_msg_generated.h"

namespace grouppack {

struct T_GROUP_CREATE_RS;

struct T_GROUP_CREATE_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_GROUP_INFO = 6,
    VT_OFFLINE_GROUP_MSG = 8,
    VT_GROUP_TYPE = 10
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  const grouppack::T_GROUP_BASE_INFO *group_info() const { return GetPointer<const grouppack::T_GROUP_BASE_INFO *>(VT_GROUP_INFO); }
  const grouppack::T_OFFLINE_GROUP_MSG *offline_group_msg() const { return GetPointer<const grouppack::T_OFFLINE_GROUP_MSG *>(VT_OFFLINE_GROUP_MSG); }
  int32_t group_type() const { return GetField<int32_t>(VT_GROUP_TYPE, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_GROUP_INFO) &&
           verifier.VerifyTable(group_info()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_OFFLINE_GROUP_MSG) &&
           verifier.VerifyTable(offline_group_msg()) &&
           VerifyField<int32_t>(verifier, VT_GROUP_TYPE) &&
           verifier.EndTable();
  }
};

struct T_GROUP_CREATE_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_GROUP_CREATE_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_group_info(flatbuffers::Offset<grouppack::T_GROUP_BASE_INFO> group_info) { fbb_.AddOffset(T_GROUP_CREATE_RS::VT_GROUP_INFO, group_info); }
  void add_offline_group_msg(flatbuffers::Offset<grouppack::T_OFFLINE_GROUP_MSG> offline_group_msg) { fbb_.AddOffset(T_GROUP_CREATE_RS::VT_OFFLINE_GROUP_MSG, offline_group_msg); }
  void add_group_type(int32_t group_type) { fbb_.AddElement<int32_t>(T_GROUP_CREATE_RS::VT_GROUP_TYPE, group_type, 0); }
  T_GROUP_CREATE_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_GROUP_CREATE_RSBuilder &operator=(const T_GROUP_CREATE_RSBuilder &);
  flatbuffers::Offset<T_GROUP_CREATE_RS> Finish() {
    auto o = flatbuffers::Offset<T_GROUP_CREATE_RS>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<T_GROUP_CREATE_RS> CreateT_GROUP_CREATE_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    flatbuffers::Offset<grouppack::T_GROUP_BASE_INFO> group_info = 0,
    flatbuffers::Offset<grouppack::T_OFFLINE_GROUP_MSG> offline_group_msg = 0,
    int32_t group_type = 0) {
  T_GROUP_CREATE_RSBuilder builder_(_fbb);
  builder_.add_group_type(group_type);
  builder_.add_offline_group_msg(offline_group_msg);
  builder_.add_group_info(group_info);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline const grouppack::T_GROUP_CREATE_RS *GetT_GROUP_CREATE_RS(const void *buf) {
  return flatbuffers::GetRoot<grouppack::T_GROUP_CREATE_RS>(buf);
}

inline bool VerifyT_GROUP_CREATE_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<grouppack::T_GROUP_CREATE_RS>(nullptr);
}

inline void FinishT_GROUP_CREATE_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<grouppack::T_GROUP_CREATE_RS> root) {
  fbb.Finish(root);
}

}  // namespace grouppack

#endif  // FLATBUFFERS_GENERATED_FBGROUPCREATERS_GROUPPACK_H_
