// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBGROUPREMARKDETAILRS_GROUPPACK_H_
#define FLATBUFFERS_GENERATED_FBGROUPREMARKDETAILRS_GROUPPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace grouppack {

struct T_GROUP_REMARK_DETAIL_RS;

struct T_GROUP_REMARK_DETAIL_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_GROUP_ID = 6,
    VT_OP_USER_ID = 8,
    VT_OP_CT = 10,
    VT_OP_REMARK = 12
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t group_id() const { return GetField<uint64_t>(VT_GROUP_ID, 0); }
  uint64_t op_user_id() const { return GetField<uint64_t>(VT_OP_USER_ID, 0); }
  uint64_t op_ct() const { return GetField<uint64_t>(VT_OP_CT, 0); }
  const flatbuffers::String *op_remark() const { return GetPointer<const flatbuffers::String *>(VT_OP_REMARK); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_GROUP_ID) &&
           VerifyField<uint64_t>(verifier, VT_OP_USER_ID) &&
           VerifyField<uint64_t>(verifier, VT_OP_CT) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_OP_REMARK) &&
           verifier.Verify(op_remark()) &&
           verifier.EndTable();
  }
};

struct T_GROUP_REMARK_DETAIL_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_GROUP_REMARK_DETAIL_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_group_id(uint64_t group_id) { fbb_.AddElement<uint64_t>(T_GROUP_REMARK_DETAIL_RS::VT_GROUP_ID, group_id, 0); }
  void add_op_user_id(uint64_t op_user_id) { fbb_.AddElement<uint64_t>(T_GROUP_REMARK_DETAIL_RS::VT_OP_USER_ID, op_user_id, 0); }
  void add_op_ct(uint64_t op_ct) { fbb_.AddElement<uint64_t>(T_GROUP_REMARK_DETAIL_RS::VT_OP_CT, op_ct, 0); }
  void add_op_remark(flatbuffers::Offset<flatbuffers::String> op_remark) { fbb_.AddOffset(T_GROUP_REMARK_DETAIL_RS::VT_OP_REMARK, op_remark); }
  T_GROUP_REMARK_DETAIL_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_GROUP_REMARK_DETAIL_RSBuilder &operator=(const T_GROUP_REMARK_DETAIL_RSBuilder &);
  flatbuffers::Offset<T_GROUP_REMARK_DETAIL_RS> Finish() {
    auto o = flatbuffers::Offset<T_GROUP_REMARK_DETAIL_RS>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<T_GROUP_REMARK_DETAIL_RS> CreateT_GROUP_REMARK_DETAIL_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t group_id = 0,
    uint64_t op_user_id = 0,
    uint64_t op_ct = 0,
    flatbuffers::Offset<flatbuffers::String> op_remark = 0) {
  T_GROUP_REMARK_DETAIL_RSBuilder builder_(_fbb);
  builder_.add_op_ct(op_ct);
  builder_.add_op_user_id(op_user_id);
  builder_.add_group_id(group_id);
  builder_.add_op_remark(op_remark);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_GROUP_REMARK_DETAIL_RS> CreateT_GROUP_REMARK_DETAIL_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t group_id = 0,
    uint64_t op_user_id = 0,
    uint64_t op_ct = 0,
    const char *op_remark = nullptr) {
  return CreateT_GROUP_REMARK_DETAIL_RS(_fbb, s_rs_head, group_id, op_user_id, op_ct, op_remark ? _fbb.CreateString(op_remark) : 0);
}

inline const grouppack::T_GROUP_REMARK_DETAIL_RS *GetT_GROUP_REMARK_DETAIL_RS(const void *buf) {
  return flatbuffers::GetRoot<grouppack::T_GROUP_REMARK_DETAIL_RS>(buf);
}

inline bool VerifyT_GROUP_REMARK_DETAIL_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<grouppack::T_GROUP_REMARK_DETAIL_RS>(nullptr);
}

inline void FinishT_GROUP_REMARK_DETAIL_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<grouppack::T_GROUP_REMARK_DETAIL_RS> root) {
  fbb.Finish(root);
}

}  // namespace grouppack

#endif  // FLATBUFFERS_GENERATED_FBGROUPREMARKDETAILRS_GROUPPACK_H_
