// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBBASERS_COMMONPACK_H_
#define FLATBUFFERS_GENERATED_FBBASERS_COMMONPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace commonpack {

struct T_BASE_RS;

struct T_BASE_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           verifier.EndTable();
  }
};

struct T_BASE_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_BASE_RS::VT_S_RS_HEAD, s_rs_head); }
  T_BASE_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_BASE_RSBuilder &operator=(const T_BASE_RSBuilder &);
  flatbuffers::Offset<T_BASE_RS> Finish() {
    auto o = flatbuffers::Offset<T_BASE_RS>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<T_BASE_RS> CreateT_BASE_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0) {
  T_BASE_RSBuilder builder_(_fbb);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline const commonpack::T_BASE_RS *GetT_BASE_RS(const void *buf) {
  return flatbuffers::GetRoot<commonpack::T_BASE_RS>(buf);
}

inline bool VerifyT_BASE_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<commonpack::T_BASE_RS>(nullptr);
}

inline void FinishT_BASE_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<commonpack::T_BASE_RS> root) {
  fbb.Finish(root);
}

}  // namespace commonpack

#endif  // FLATBUFFERS_GENERATED_FBBASERS_COMMONPACK_H_
