// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBECGETPROMPTSRS_ECPACK_H_
#define FLATBUFFERS_GENERATED_FBECGETPROMPTSRS_ECPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "fb_ec_promptmsginfo_generated.h"

namespace ecpack {

struct T_EC_GETPROMPTS_RS;

struct T_EC_GETPROMPTS_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_PROMPTSMSGLIST = 6
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  const flatbuffers::Vector<flatbuffers::Offset<ecpack::T_PROMPTMSG_INFO>> *promptsmsglist() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ecpack::T_PROMPTMSG_INFO>> *>(VT_PROMPTSMSGLIST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PROMPTSMSGLIST) &&
           verifier.Verify(promptsmsglist()) &&
           verifier.VerifyVectorOfTables(promptsmsglist()) &&
           verifier.EndTable();
  }
};

struct T_EC_GETPROMPTS_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_EC_GETPROMPTS_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_promptsmsglist(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ecpack::T_PROMPTMSG_INFO>>> promptsmsglist) { fbb_.AddOffset(T_EC_GETPROMPTS_RS::VT_PROMPTSMSGLIST, promptsmsglist); }
  T_EC_GETPROMPTS_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_EC_GETPROMPTS_RSBuilder &operator=(const T_EC_GETPROMPTS_RSBuilder &);
  flatbuffers::Offset<T_EC_GETPROMPTS_RS> Finish() {
    auto o = flatbuffers::Offset<T_EC_GETPROMPTS_RS>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_EC_GETPROMPTS_RS> CreateT_EC_GETPROMPTS_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ecpack::T_PROMPTMSG_INFO>>> promptsmsglist = 0) {
  T_EC_GETPROMPTS_RSBuilder builder_(_fbb);
  builder_.add_promptsmsglist(promptsmsglist);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_EC_GETPROMPTS_RS> CreateT_EC_GETPROMPTS_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    const std::vector<flatbuffers::Offset<ecpack::T_PROMPTMSG_INFO>> *promptsmsglist = nullptr) {
  return CreateT_EC_GETPROMPTS_RS(_fbb, s_rs_head, promptsmsglist ? _fbb.CreateVector<flatbuffers::Offset<ecpack::T_PROMPTMSG_INFO>>(*promptsmsglist) : 0);
}

inline const ecpack::T_EC_GETPROMPTS_RS *GetT_EC_GETPROMPTS_RS(const void *buf) {
  return flatbuffers::GetRoot<ecpack::T_EC_GETPROMPTS_RS>(buf);
}

inline bool VerifyT_EC_GETPROMPTS_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ecpack::T_EC_GETPROMPTS_RS>(nullptr);
}

inline void FinishT_EC_GETPROMPTS_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ecpack::T_EC_GETPROMPTS_RS> root) {
  fbb.Finish(root);
}

}  // namespace ecpack

#endif  // FLATBUFFERS_GENERATED_FBECGETPROMPTSRS_ECPACK_H_
