// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBECSETBUSINESSRS_ECPACK_H_
#define FLATBUFFERS_GENERATED_FBECSETBUSINESSRS_ECPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace ecpack {

struct T_EC_SETBUSINESS_RS;

struct T_EC_SETBUSINESS_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_SELLERID = 6
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t sellerId() const { return GetField<uint64_t>(VT_SELLERID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_SELLERID) &&
           verifier.EndTable();
  }
};

struct T_EC_SETBUSINESS_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_EC_SETBUSINESS_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_sellerId(uint64_t sellerId) { fbb_.AddElement<uint64_t>(T_EC_SETBUSINESS_RS::VT_SELLERID, sellerId, 0); }
  T_EC_SETBUSINESS_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_EC_SETBUSINESS_RSBuilder &operator=(const T_EC_SETBUSINESS_RSBuilder &);
  flatbuffers::Offset<T_EC_SETBUSINESS_RS> Finish() {
    auto o = flatbuffers::Offset<T_EC_SETBUSINESS_RS>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_EC_SETBUSINESS_RS> CreateT_EC_SETBUSINESS_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t sellerId = 0) {
  T_EC_SETBUSINESS_RSBuilder builder_(_fbb);
  builder_.add_sellerId(sellerId);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline const ecpack::T_EC_SETBUSINESS_RS *GetT_EC_SETBUSINESS_RS(const void *buf) {
  return flatbuffers::GetRoot<ecpack::T_EC_SETBUSINESS_RS>(buf);
}

inline bool VerifyT_EC_SETBUSINESS_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ecpack::T_EC_SETBUSINESS_RS>(nullptr);
}

inline void FinishT_EC_SETBUSINESS_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ecpack::T_EC_SETBUSINESS_RS> root) {
  fbb.Finish(root);
}

}  // namespace ecpack

#endif  // FLATBUFFERS_GENERATED_FBECSETBUSINESSRS_ECPACK_H_
