// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBECSETLOGINSTATUSRQ_ECPACK_H_
#define FLATBUFFERS_GENERATED_FBECSETLOGINSTATUSRQ_ECPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace ecpack {

struct T_EC_SET_LOGINSTATUS_RQ;

struct T_EC_SET_LOGINSTATUS_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_STATUS = 6
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  int32_t status() const { return GetField<int32_t>(VT_STATUS, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<int32_t>(verifier, VT_STATUS) &&
           verifier.EndTable();
  }
};

struct T_EC_SET_LOGINSTATUS_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_EC_SET_LOGINSTATUS_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_status(int32_t status) { fbb_.AddElement<int32_t>(T_EC_SET_LOGINSTATUS_RQ::VT_STATUS, status, 0); }
  T_EC_SET_LOGINSTATUS_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_EC_SET_LOGINSTATUS_RQBuilder &operator=(const T_EC_SET_LOGINSTATUS_RQBuilder &);
  flatbuffers::Offset<T_EC_SET_LOGINSTATUS_RQ> Finish() {
    auto o = flatbuffers::Offset<T_EC_SET_LOGINSTATUS_RQ>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_EC_SET_LOGINSTATUS_RQ> CreateT_EC_SET_LOGINSTATUS_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    int32_t status = 0) {
  T_EC_SET_LOGINSTATUS_RQBuilder builder_(_fbb);
  builder_.add_status(status);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline const ecpack::T_EC_SET_LOGINSTATUS_RQ *GetT_EC_SET_LOGINSTATUS_RQ(const void *buf) {
  return flatbuffers::GetRoot<ecpack::T_EC_SET_LOGINSTATUS_RQ>(buf);
}

inline bool VerifyT_EC_SET_LOGINSTATUS_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ecpack::T_EC_SET_LOGINSTATUS_RQ>(nullptr);
}

inline void FinishT_EC_SET_LOGINSTATUS_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ecpack::T_EC_SET_LOGINSTATUS_RQ> root) {
  fbb.Finish(root);
}

}  // namespace ecpack

#endif  // FLATBUFFERS_GENERATED_FBECSETLOGINSTATUSRQ_ECPACK_H_
