// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBECGETFREEWAITERRS_ECPACK_H_
#define FLATBUFFERS_GENERATED_FBECGETFREEWAITERRS_ECPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace ecpack {

struct T_EC_GETFREEWAITER_RS;

struct T_EC_GETFREEWAITER_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_B_ID = 6,
    VT_W_ID = 8,
    VT_SESSION_ID = 10,
    VT_PROMTPSMSG = 12
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t b_id() const { return GetField<uint64_t>(VT_B_ID, 0); }
  uint64_t w_id() const { return GetField<uint64_t>(VT_W_ID, 0); }
  int32_t session_id() const { return GetField<int32_t>(VT_SESSION_ID, 0); }
  const flatbuffers::String *promtpsmsg() const { return GetPointer<const flatbuffers::String *>(VT_PROMTPSMSG); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_B_ID) &&
           VerifyField<uint64_t>(verifier, VT_W_ID) &&
           VerifyField<int32_t>(verifier, VT_SESSION_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PROMTPSMSG) &&
           verifier.Verify(promtpsmsg()) &&
           verifier.EndTable();
  }
};

struct T_EC_GETFREEWAITER_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_EC_GETFREEWAITER_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_b_id(uint64_t b_id) { fbb_.AddElement<uint64_t>(T_EC_GETFREEWAITER_RS::VT_B_ID, b_id, 0); }
  void add_w_id(uint64_t w_id) { fbb_.AddElement<uint64_t>(T_EC_GETFREEWAITER_RS::VT_W_ID, w_id, 0); }
  void add_session_id(int32_t session_id) { fbb_.AddElement<int32_t>(T_EC_GETFREEWAITER_RS::VT_SESSION_ID, session_id, 0); }
  void add_promtpsmsg(flatbuffers::Offset<flatbuffers::String> promtpsmsg) { fbb_.AddOffset(T_EC_GETFREEWAITER_RS::VT_PROMTPSMSG, promtpsmsg); }
  T_EC_GETFREEWAITER_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_EC_GETFREEWAITER_RSBuilder &operator=(const T_EC_GETFREEWAITER_RSBuilder &);
  flatbuffers::Offset<T_EC_GETFREEWAITER_RS> Finish() {
    auto o = flatbuffers::Offset<T_EC_GETFREEWAITER_RS>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<T_EC_GETFREEWAITER_RS> CreateT_EC_GETFREEWAITER_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t b_id = 0,
    uint64_t w_id = 0,
    int32_t session_id = 0,
    flatbuffers::Offset<flatbuffers::String> promtpsmsg = 0) {
  T_EC_GETFREEWAITER_RSBuilder builder_(_fbb);
  builder_.add_w_id(w_id);
  builder_.add_b_id(b_id);
  builder_.add_promtpsmsg(promtpsmsg);
  builder_.add_session_id(session_id);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_EC_GETFREEWAITER_RS> CreateT_EC_GETFREEWAITER_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t b_id = 0,
    uint64_t w_id = 0,
    int32_t session_id = 0,
    const char *promtpsmsg = nullptr) {
  return CreateT_EC_GETFREEWAITER_RS(_fbb, s_rs_head, b_id, w_id, session_id, promtpsmsg ? _fbb.CreateString(promtpsmsg) : 0);
}

inline const ecpack::T_EC_GETFREEWAITER_RS *GetT_EC_GETFREEWAITER_RS(const void *buf) {
  return flatbuffers::GetRoot<ecpack::T_EC_GETFREEWAITER_RS>(buf);
}

inline bool VerifyT_EC_GETFREEWAITER_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ecpack::T_EC_GETFREEWAITER_RS>(nullptr);
}

inline void FinishT_EC_GETFREEWAITER_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ecpack::T_EC_GETFREEWAITER_RS> root) {
  fbb.Finish(root);
}

}  // namespace ecpack

#endif  // FLATBUFFERS_GENERATED_FBECGETFREEWAITERRS_ECPACK_H_
