// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBECGETRECENTORDERSRS_ECPACK_H_
#define FLATBUFFERS_GENERATED_FBECGETRECENTORDERSRS_ECPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "fb_ec_goodsinfotoims_generated.h"
#include "fb_ec_orderinfo_generated.h"

namespace ecpack {

struct T_EC_GETRECENTORDERS_RS;

struct T_EC_GETRECENTORDERS_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_CODE = 6,
    VT_ORDER_LIST = 8
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  int32_t code() const { return GetField<int32_t>(VT_CODE, 0); }
  const flatbuffers::Vector<flatbuffers::Offset<ecpack::T_ORDER_INFO>> *order_list() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ecpack::T_ORDER_INFO>> *>(VT_ORDER_LIST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<int32_t>(verifier, VT_CODE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_ORDER_LIST) &&
           verifier.Verify(order_list()) &&
           verifier.VerifyVectorOfTables(order_list()) &&
           verifier.EndTable();
  }
};

struct T_EC_GETRECENTORDERS_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_EC_GETRECENTORDERS_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_code(int32_t code) { fbb_.AddElement<int32_t>(T_EC_GETRECENTORDERS_RS::VT_CODE, code, 0); }
  void add_order_list(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ecpack::T_ORDER_INFO>>> order_list) { fbb_.AddOffset(T_EC_GETRECENTORDERS_RS::VT_ORDER_LIST, order_list); }
  T_EC_GETRECENTORDERS_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_EC_GETRECENTORDERS_RSBuilder &operator=(const T_EC_GETRECENTORDERS_RSBuilder &);
  flatbuffers::Offset<T_EC_GETRECENTORDERS_RS> Finish() {
    auto o = flatbuffers::Offset<T_EC_GETRECENTORDERS_RS>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<T_EC_GETRECENTORDERS_RS> CreateT_EC_GETRECENTORDERS_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    int32_t code = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ecpack::T_ORDER_INFO>>> order_list = 0) {
  T_EC_GETRECENTORDERS_RSBuilder builder_(_fbb);
  builder_.add_order_list(order_list);
  builder_.add_code(code);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_EC_GETRECENTORDERS_RS> CreateT_EC_GETRECENTORDERS_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    int32_t code = 0,
    const std::vector<flatbuffers::Offset<ecpack::T_ORDER_INFO>> *order_list = nullptr) {
  return CreateT_EC_GETRECENTORDERS_RS(_fbb, s_rs_head, code, order_list ? _fbb.CreateVector<flatbuffers::Offset<ecpack::T_ORDER_INFO>>(*order_list) : 0);
}

inline const ecpack::T_EC_GETRECENTORDERS_RS *GetT_EC_GETRECENTORDERS_RS(const void *buf) {
  return flatbuffers::GetRoot<ecpack::T_EC_GETRECENTORDERS_RS>(buf);
}

inline bool VerifyT_EC_GETRECENTORDERS_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ecpack::T_EC_GETRECENTORDERS_RS>(nullptr);
}

inline void FinishT_EC_GETRECENTORDERS_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ecpack::T_EC_GETRECENTORDERS_RS> root) {
  fbb.Finish(root);
}

}  // namespace ecpack

#endif  // FLATBUFFERS_GENERATED_FBECGETRECENTORDERSRS_ECPACK_H_
