// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBECGETBUSINESSRS_ECPACK_H_
#define FLATBUFFERS_GENERATED_FBECGETBUSINESSRS_ECPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace ecpack {

struct T_EC_GETBUSINESS_RS;

struct T_EC_GETBUSINESS_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_SELLERID = 6,
    VT_SELLERTYPE = 8,
    VT_SELLERAVATAR = 10,
    VT_SELLERNAME = 12,
    VT_SELLERURL = 14
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t sellerId() const { return GetField<uint64_t>(VT_SELLERID, 0); }
  int32_t sellerType() const { return GetField<int32_t>(VT_SELLERTYPE, 0); }
  const flatbuffers::String *sellerAvatar() const { return GetPointer<const flatbuffers::String *>(VT_SELLERAVATAR); }
  const flatbuffers::String *sellerName() const { return GetPointer<const flatbuffers::String *>(VT_SELLERNAME); }
  const flatbuffers::String *sellerUrl() const { return GetPointer<const flatbuffers::String *>(VT_SELLERURL); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_SELLERID) &&
           VerifyField<int32_t>(verifier, VT_SELLERTYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_SELLERAVATAR) &&
           verifier.Verify(sellerAvatar()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_SELLERNAME) &&
           verifier.Verify(sellerName()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_SELLERURL) &&
           verifier.Verify(sellerUrl()) &&
           verifier.EndTable();
  }
};

struct T_EC_GETBUSINESS_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_EC_GETBUSINESS_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_sellerId(uint64_t sellerId) { fbb_.AddElement<uint64_t>(T_EC_GETBUSINESS_RS::VT_SELLERID, sellerId, 0); }
  void add_sellerType(int32_t sellerType) { fbb_.AddElement<int32_t>(T_EC_GETBUSINESS_RS::VT_SELLERTYPE, sellerType, 0); }
  void add_sellerAvatar(flatbuffers::Offset<flatbuffers::String> sellerAvatar) { fbb_.AddOffset(T_EC_GETBUSINESS_RS::VT_SELLERAVATAR, sellerAvatar); }
  void add_sellerName(flatbuffers::Offset<flatbuffers::String> sellerName) { fbb_.AddOffset(T_EC_GETBUSINESS_RS::VT_SELLERNAME, sellerName); }
  void add_sellerUrl(flatbuffers::Offset<flatbuffers::String> sellerUrl) { fbb_.AddOffset(T_EC_GETBUSINESS_RS::VT_SELLERURL, sellerUrl); }
  T_EC_GETBUSINESS_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_EC_GETBUSINESS_RSBuilder &operator=(const T_EC_GETBUSINESS_RSBuilder &);
  flatbuffers::Offset<T_EC_GETBUSINESS_RS> Finish() {
    auto o = flatbuffers::Offset<T_EC_GETBUSINESS_RS>(fbb_.EndTable(start_, 6));
    return o;
  }
};

inline flatbuffers::Offset<T_EC_GETBUSINESS_RS> CreateT_EC_GETBUSINESS_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t sellerId = 0,
    int32_t sellerType = 0,
    flatbuffers::Offset<flatbuffers::String> sellerAvatar = 0,
    flatbuffers::Offset<flatbuffers::String> sellerName = 0,
    flatbuffers::Offset<flatbuffers::String> sellerUrl = 0) {
  T_EC_GETBUSINESS_RSBuilder builder_(_fbb);
  builder_.add_sellerId(sellerId);
  builder_.add_sellerUrl(sellerUrl);
  builder_.add_sellerName(sellerName);
  builder_.add_sellerAvatar(sellerAvatar);
  builder_.add_sellerType(sellerType);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_EC_GETBUSINESS_RS> CreateT_EC_GETBUSINESS_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t sellerId = 0,
    int32_t sellerType = 0,
    const char *sellerAvatar = nullptr,
    const char *sellerName = nullptr,
    const char *sellerUrl = nullptr) {
  return CreateT_EC_GETBUSINESS_RS(_fbb, s_rs_head, sellerId, sellerType, sellerAvatar ? _fbb.CreateString(sellerAvatar) : 0, sellerName ? _fbb.CreateString(sellerName) : 0, sellerUrl ? _fbb.CreateString(sellerUrl) : 0);
}

inline const ecpack::T_EC_GETBUSINESS_RS *GetT_EC_GETBUSINESS_RS(const void *buf) {
  return flatbuffers::GetRoot<ecpack::T_EC_GETBUSINESS_RS>(buf);
}

inline bool VerifyT_EC_GETBUSINESS_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ecpack::T_EC_GETBUSINESS_RS>(nullptr);
}

inline void FinishT_EC_GETBUSINESS_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ecpack::T_EC_GETBUSINESS_RS> root) {
  fbb.Finish(root);
}

}  // namespace ecpack

#endif  // FLATBUFFERS_GENERATED_FBECGETBUSINESSRS_ECPACK_H_
