// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBECGETPROMPTSRQ_ECPACK_H_
#define FLATBUFFERS_GENERATED_FBECGETPROMPTSRQ_ECPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "fb_ec_promptmsginfo_generated.h"

namespace ecpack {

struct T_EC_GETPROMPTS_RQ;

struct T_EC_GETPROMPTS_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_B_ID_LIST = 6
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  const flatbuffers::Vector<uint64_t> *b_id_list() const { return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_B_ID_LIST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_B_ID_LIST) &&
           verifier.Verify(b_id_list()) &&
           verifier.EndTable();
  }
};

struct T_EC_GETPROMPTS_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_EC_GETPROMPTS_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_b_id_list(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> b_id_list) { fbb_.AddOffset(T_EC_GETPROMPTS_RQ::VT_B_ID_LIST, b_id_list); }
  T_EC_GETPROMPTS_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_EC_GETPROMPTS_RQBuilder &operator=(const T_EC_GETPROMPTS_RQBuilder &);
  flatbuffers::Offset<T_EC_GETPROMPTS_RQ> Finish() {
    auto o = flatbuffers::Offset<T_EC_GETPROMPTS_RQ>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_EC_GETPROMPTS_RQ> CreateT_EC_GETPROMPTS_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> b_id_list = 0) {
  T_EC_GETPROMPTS_RQBuilder builder_(_fbb);
  builder_.add_b_id_list(b_id_list);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_EC_GETPROMPTS_RQ> CreateT_EC_GETPROMPTS_RQDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    const std::vector<uint64_t> *b_id_list = nullptr) {
  return CreateT_EC_GETPROMPTS_RQ(_fbb, s_rq_head, b_id_list ? _fbb.CreateVector<uint64_t>(*b_id_list) : 0);
}

inline const ecpack::T_EC_GETPROMPTS_RQ *GetT_EC_GETPROMPTS_RQ(const void *buf) {
  return flatbuffers::GetRoot<ecpack::T_EC_GETPROMPTS_RQ>(buf);
}

inline bool VerifyT_EC_GETPROMPTS_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ecpack::T_EC_GETPROMPTS_RQ>(nullptr);
}

inline void FinishT_EC_GETPROMPTS_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ecpack::T_EC_GETPROMPTS_RQ> root) {
  fbb.Finish(root);
}

}  // namespace ecpack

#endif  // FLATBUFFERS_GENERATED_FBECGETPROMPTSRQ_ECPACK_H_
