// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBECGETRECENTUSERSRS_ECPACK_H_
#define FLATBUFFERS_GENERATED_FBECGETRECENTUSERSRS_ECPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace ecpack {

struct T_EC_GETRECENTUSERS_RS;

struct T_EC_GETRECENTUSERS_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_B_ID = 6,
    VT_C_ID_LIST = 8
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t b_id() const { return GetField<uint64_t>(VT_B_ID, 0); }
  const flatbuffers::Vector<uint64_t> *c_id_list() const { return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_C_ID_LIST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_B_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_C_ID_LIST) &&
           verifier.Verify(c_id_list()) &&
           verifier.EndTable();
  }
};

struct T_EC_GETRECENTUSERS_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_EC_GETRECENTUSERS_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_b_id(uint64_t b_id) { fbb_.AddElement<uint64_t>(T_EC_GETRECENTUSERS_RS::VT_B_ID, b_id, 0); }
  void add_c_id_list(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> c_id_list) { fbb_.AddOffset(T_EC_GETRECENTUSERS_RS::VT_C_ID_LIST, c_id_list); }
  T_EC_GETRECENTUSERS_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_EC_GETRECENTUSERS_RSBuilder &operator=(const T_EC_GETRECENTUSERS_RSBuilder &);
  flatbuffers::Offset<T_EC_GETRECENTUSERS_RS> Finish() {
    auto o = flatbuffers::Offset<T_EC_GETRECENTUSERS_RS>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<T_EC_GETRECENTUSERS_RS> CreateT_EC_GETRECENTUSERS_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t b_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> c_id_list = 0) {
  T_EC_GETRECENTUSERS_RSBuilder builder_(_fbb);
  builder_.add_b_id(b_id);
  builder_.add_c_id_list(c_id_list);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_EC_GETRECENTUSERS_RS> CreateT_EC_GETRECENTUSERS_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t b_id = 0,
    const std::vector<uint64_t> *c_id_list = nullptr) {
  return CreateT_EC_GETRECENTUSERS_RS(_fbb, s_rs_head, b_id, c_id_list ? _fbb.CreateVector<uint64_t>(*c_id_list) : 0);
}

inline const ecpack::T_EC_GETRECENTUSERS_RS *GetT_EC_GETRECENTUSERS_RS(const void *buf) {
  return flatbuffers::GetRoot<ecpack::T_EC_GETRECENTUSERS_RS>(buf);
}

inline bool VerifyT_EC_GETRECENTUSERS_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ecpack::T_EC_GETRECENTUSERS_RS>(nullptr);
}

inline void FinishT_EC_GETRECENTUSERS_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ecpack::T_EC_GETRECENTUSERS_RS> root) {
  fbb.Finish(root);
}

}  // namespace ecpack

#endif  // FLATBUFFERS_GENERATED_FBECGETRECENTUSERSRS_ECPACK_H_
