// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBCLIENTFANSGETSYSMSGRQ_OFFCIALPACK_H_
#define FLATBUFFERS_GENERATED_FBCLIENTFANSGETSYSMSGRQ_OFFCIALPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace offcialpack {

struct T_CLIENT_FANS_GET_SYS_MSG_RQ;

struct T_CLIENT_FANS_GET_SYS_MSG_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_MESSAGE_ID = 6
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  uint64_t message_id() const { return GetField<uint64_t>(VT_MESSAGE_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_MESSAGE_ID) &&
           verifier.EndTable();
  }
};

struct T_CLIENT_FANS_GET_SYS_MSG_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_CLIENT_FANS_GET_SYS_MSG_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_message_id(uint64_t message_id) { fbb_.AddElement<uint64_t>(T_CLIENT_FANS_GET_SYS_MSG_RQ::VT_MESSAGE_ID, message_id, 0); }
  T_CLIENT_FANS_GET_SYS_MSG_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_CLIENT_FANS_GET_SYS_MSG_RQBuilder &operator=(const T_CLIENT_FANS_GET_SYS_MSG_RQBuilder &);
  flatbuffers::Offset<T_CLIENT_FANS_GET_SYS_MSG_RQ> Finish() {
    auto o = flatbuffers::Offset<T_CLIENT_FANS_GET_SYS_MSG_RQ>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_CLIENT_FANS_GET_SYS_MSG_RQ> CreateT_CLIENT_FANS_GET_SYS_MSG_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t message_id = 0) {
  T_CLIENT_FANS_GET_SYS_MSG_RQBuilder builder_(_fbb);
  builder_.add_message_id(message_id);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline const offcialpack::T_CLIENT_FANS_GET_SYS_MSG_RQ *GetT_CLIENT_FANS_GET_SYS_MSG_RQ(const void *buf) {
  return flatbuffers::GetRoot<offcialpack::T_CLIENT_FANS_GET_SYS_MSG_RQ>(buf);
}

inline bool VerifyT_CLIENT_FANS_GET_SYS_MSG_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<offcialpack::T_CLIENT_FANS_GET_SYS_MSG_RQ>(nullptr);
}

inline void FinishT_CLIENT_FANS_GET_SYS_MSG_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<offcialpack::T_CLIENT_FANS_GET_SYS_MSG_RQ> root) {
  fbb.Finish(root);
}

}  // namespace offcialpack

#endif  // FLATBUFFERS_GENERATED_FBCLIENTFANSGETSYSMSGRQ_OFFCIALPACK_H_
