// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBOFFCIALOFFLINEMSG_OFFCIALPACK_H_
#define FLATBUFFERS_GENERATED_FBOFFCIALOFFLINEMSG_OFFCIALPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace offcialpack {

struct T_OFFLINE_MESSAGE;

struct T_OFFCIAL_OFFLINE_MESSAGE;

struct T_OFFLINE_MESSAGE FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_MESSAGE_ID = 4,
    VT_S_MSG = 6
  };
  uint64_t message_id() const { return GetField<uint64_t>(VT_MESSAGE_ID, 0); }
  const commonpack::S_MSG *s_msg() const { return GetPointer<const commonpack::S_MSG *>(VT_S_MSG); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_MESSAGE_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_S_MSG) &&
           verifier.VerifyTable(s_msg()) &&
           verifier.EndTable();
  }
};

struct T_OFFLINE_MESSAGEBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_message_id(uint64_t message_id) { fbb_.AddElement<uint64_t>(T_OFFLINE_MESSAGE::VT_MESSAGE_ID, message_id, 0); }
  void add_s_msg(flatbuffers::Offset<commonpack::S_MSG> s_msg) { fbb_.AddOffset(T_OFFLINE_MESSAGE::VT_S_MSG, s_msg); }
  T_OFFLINE_MESSAGEBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_OFFLINE_MESSAGEBuilder &operator=(const T_OFFLINE_MESSAGEBuilder &);
  flatbuffers::Offset<T_OFFLINE_MESSAGE> Finish() {
    auto o = flatbuffers::Offset<T_OFFLINE_MESSAGE>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_OFFLINE_MESSAGE> CreateT_OFFLINE_MESSAGE(flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t message_id = 0,
    flatbuffers::Offset<commonpack::S_MSG> s_msg = 0) {
  T_OFFLINE_MESSAGEBuilder builder_(_fbb);
  builder_.add_message_id(message_id);
  builder_.add_s_msg(s_msg);
  return builder_.Finish();
}

struct T_OFFCIAL_OFFLINE_MESSAGE FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_IS_FINISH = 4,
    VT_OFFCIAL_ID = 6,
    VT_S_MSG = 8,
    VT_B_ID = 10,
    VT_W_ID = 12,
    VT_C_ID = 14
  };
  int8_t is_finish() const { return GetField<int8_t>(VT_IS_FINISH, 0); }
  uint64_t offcial_id() const { return GetField<uint64_t>(VT_OFFCIAL_ID, 0); }
  const flatbuffers::Vector<flatbuffers::Offset<T_OFFLINE_MESSAGE>> *s_msg() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<T_OFFLINE_MESSAGE>> *>(VT_S_MSG); }
  uint64_t b_id() const { return GetField<uint64_t>(VT_B_ID, 0); }
  uint64_t w_id() const { return GetField<uint64_t>(VT_W_ID, 0); }
  uint64_t c_id() const { return GetField<uint64_t>(VT_C_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_IS_FINISH) &&
           VerifyField<uint64_t>(verifier, VT_OFFCIAL_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_S_MSG) &&
           verifier.Verify(s_msg()) &&
           verifier.VerifyVectorOfTables(s_msg()) &&
           VerifyField<uint64_t>(verifier, VT_B_ID) &&
           VerifyField<uint64_t>(verifier, VT_W_ID) &&
           VerifyField<uint64_t>(verifier, VT_C_ID) &&
           verifier.EndTable();
  }
};

struct T_OFFCIAL_OFFLINE_MESSAGEBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_is_finish(int8_t is_finish) { fbb_.AddElement<int8_t>(T_OFFCIAL_OFFLINE_MESSAGE::VT_IS_FINISH, is_finish, 0); }
  void add_offcial_id(uint64_t offcial_id) { fbb_.AddElement<uint64_t>(T_OFFCIAL_OFFLINE_MESSAGE::VT_OFFCIAL_ID, offcial_id, 0); }
  void add_s_msg(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<T_OFFLINE_MESSAGE>>> s_msg) { fbb_.AddOffset(T_OFFCIAL_OFFLINE_MESSAGE::VT_S_MSG, s_msg); }
  void add_b_id(uint64_t b_id) { fbb_.AddElement<uint64_t>(T_OFFCIAL_OFFLINE_MESSAGE::VT_B_ID, b_id, 0); }
  void add_w_id(uint64_t w_id) { fbb_.AddElement<uint64_t>(T_OFFCIAL_OFFLINE_MESSAGE::VT_W_ID, w_id, 0); }
  void add_c_id(uint64_t c_id) { fbb_.AddElement<uint64_t>(T_OFFCIAL_OFFLINE_MESSAGE::VT_C_ID, c_id, 0); }
  T_OFFCIAL_OFFLINE_MESSAGEBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_OFFCIAL_OFFLINE_MESSAGEBuilder &operator=(const T_OFFCIAL_OFFLINE_MESSAGEBuilder &);
  flatbuffers::Offset<T_OFFCIAL_OFFLINE_MESSAGE> Finish() {
    auto o = flatbuffers::Offset<T_OFFCIAL_OFFLINE_MESSAGE>(fbb_.EndTable(start_, 6));
    return o;
  }
};

inline flatbuffers::Offset<T_OFFCIAL_OFFLINE_MESSAGE> CreateT_OFFCIAL_OFFLINE_MESSAGE(flatbuffers::FlatBufferBuilder &_fbb,
    int8_t is_finish = 0,
    uint64_t offcial_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<T_OFFLINE_MESSAGE>>> s_msg = 0,
    uint64_t b_id = 0,
    uint64_t w_id = 0,
    uint64_t c_id = 0) {
  T_OFFCIAL_OFFLINE_MESSAGEBuilder builder_(_fbb);
  builder_.add_c_id(c_id);
  builder_.add_w_id(w_id);
  builder_.add_b_id(b_id);
  builder_.add_offcial_id(offcial_id);
  builder_.add_s_msg(s_msg);
  builder_.add_is_finish(is_finish);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_OFFCIAL_OFFLINE_MESSAGE> CreateT_OFFCIAL_OFFLINE_MESSAGEDirect(flatbuffers::FlatBufferBuilder &_fbb,
    int8_t is_finish = 0,
    uint64_t offcial_id = 0,
    const std::vector<flatbuffers::Offset<T_OFFLINE_MESSAGE>> *s_msg = nullptr,
    uint64_t b_id = 0,
    uint64_t w_id = 0,
    uint64_t c_id = 0) {
  return CreateT_OFFCIAL_OFFLINE_MESSAGE(_fbb, is_finish, offcial_id, s_msg ? _fbb.CreateVector<flatbuffers::Offset<T_OFFLINE_MESSAGE>>(*s_msg) : 0, b_id, w_id, c_id);
}

inline const offcialpack::T_OFFCIAL_OFFLINE_MESSAGE *GetT_OFFCIAL_OFFLINE_MESSAGE(const void *buf) {
  return flatbuffers::GetRoot<offcialpack::T_OFFCIAL_OFFLINE_MESSAGE>(buf);
}

inline bool VerifyT_OFFCIAL_OFFLINE_MESSAGEBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<offcialpack::T_OFFCIAL_OFFLINE_MESSAGE>(nullptr);
}

inline void FinishT_OFFCIAL_OFFLINE_MESSAGEBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<offcialpack::T_OFFCIAL_OFFLINE_MESSAGE> root) {
  fbb.Finish(root);
}

}  // namespace offcialpack

#endif  // FLATBUFFERS_GENERATED_FBOFFCIALOFFLINEMSG_OFFCIALPACK_H_
