// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBCHANGEMAILRQ_USERPACK_H_
#define FLATBUFFERS_GENERATED_FBCHANGEMAILRQ_USERPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace userpack {

struct T_CHANGE_MAIL_RQ;

struct T_CHANGE_MAIL_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_OLD_MAIL = 6,
    VT_NEW_MAIL = 8
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  const flatbuffers::String *old_mail() const { return GetPointer<const flatbuffers::String *>(VT_OLD_MAIL); }
  const flatbuffers::String *new_mail() const { return GetPointer<const flatbuffers::String *>(VT_NEW_MAIL); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_OLD_MAIL) &&
           verifier.Verify(old_mail()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NEW_MAIL) &&
           verifier.Verify(new_mail()) &&
           verifier.EndTable();
  }
};

struct T_CHANGE_MAIL_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_CHANGE_MAIL_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_old_mail(flatbuffers::Offset<flatbuffers::String> old_mail) { fbb_.AddOffset(T_CHANGE_MAIL_RQ::VT_OLD_MAIL, old_mail); }
  void add_new_mail(flatbuffers::Offset<flatbuffers::String> new_mail) { fbb_.AddOffset(T_CHANGE_MAIL_RQ::VT_NEW_MAIL, new_mail); }
  T_CHANGE_MAIL_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_CHANGE_MAIL_RQBuilder &operator=(const T_CHANGE_MAIL_RQBuilder &);
  flatbuffers::Offset<T_CHANGE_MAIL_RQ> Finish() {
    auto o = flatbuffers::Offset<T_CHANGE_MAIL_RQ>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<T_CHANGE_MAIL_RQ> CreateT_CHANGE_MAIL_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    flatbuffers::Offset<flatbuffers::String> old_mail = 0,
    flatbuffers::Offset<flatbuffers::String> new_mail = 0) {
  T_CHANGE_MAIL_RQBuilder builder_(_fbb);
  builder_.add_new_mail(new_mail);
  builder_.add_old_mail(old_mail);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_CHANGE_MAIL_RQ> CreateT_CHANGE_MAIL_RQDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    const char *old_mail = nullptr,
    const char *new_mail = nullptr) {
  return CreateT_CHANGE_MAIL_RQ(_fbb, s_rq_head, old_mail ? _fbb.CreateString(old_mail) : 0, new_mail ? _fbb.CreateString(new_mail) : 0);
}

inline const userpack::T_CHANGE_MAIL_RQ *GetT_CHANGE_MAIL_RQ(const void *buf) {
  return flatbuffers::GetRoot<userpack::T_CHANGE_MAIL_RQ>(buf);
}

inline bool VerifyT_CHANGE_MAIL_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<userpack::T_CHANGE_MAIL_RQ>(nullptr);
}

inline void FinishT_CHANGE_MAIL_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<userpack::T_CHANGE_MAIL_RQ> root) {
  fbb.Finish(root);
}

}  // namespace userpack

#endif  // FLATBUFFERS_GENERATED_FBCHANGEMAILRQ_USERPACK_H_
