// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBGETUSERLSTINFORQ_USERPACK_H_
#define FLATBUFFERS_GENERATED_FBGETUSERLSTINFORQ_USERPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace userpack {

struct T_GET_USERLST_INFO_RQ;

struct T_GET_USERLST_INFO_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_USERLST = 6,
    VT_MOBILELST = 8
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  const flatbuffers::Vector<uint64_t> *userLst() const { return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_USERLST); }
  const flatbuffers::Vector<uint64_t> *mobileLst() const { return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_MOBILELST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_USERLST) &&
           verifier.Verify(userLst()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_MOBILELST) &&
           verifier.Verify(mobileLst()) &&
           verifier.EndTable();
  }
};

struct T_GET_USERLST_INFO_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_GET_USERLST_INFO_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_userLst(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> userLst) { fbb_.AddOffset(T_GET_USERLST_INFO_RQ::VT_USERLST, userLst); }
  void add_mobileLst(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> mobileLst) { fbb_.AddOffset(T_GET_USERLST_INFO_RQ::VT_MOBILELST, mobileLst); }
  T_GET_USERLST_INFO_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_GET_USERLST_INFO_RQBuilder &operator=(const T_GET_USERLST_INFO_RQBuilder &);
  flatbuffers::Offset<T_GET_USERLST_INFO_RQ> Finish() {
    auto o = flatbuffers::Offset<T_GET_USERLST_INFO_RQ>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<T_GET_USERLST_INFO_RQ> CreateT_GET_USERLST_INFO_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> userLst = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> mobileLst = 0) {
  T_GET_USERLST_INFO_RQBuilder builder_(_fbb);
  builder_.add_mobileLst(mobileLst);
  builder_.add_userLst(userLst);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_GET_USERLST_INFO_RQ> CreateT_GET_USERLST_INFO_RQDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    const std::vector<uint64_t> *userLst = nullptr,
    const std::vector<uint64_t> *mobileLst = nullptr) {
  return CreateT_GET_USERLST_INFO_RQ(_fbb, s_rq_head, userLst ? _fbb.CreateVector<uint64_t>(*userLst) : 0, mobileLst ? _fbb.CreateVector<uint64_t>(*mobileLst) : 0);
}

inline const userpack::T_GET_USERLST_INFO_RQ *GetT_GET_USERLST_INFO_RQ(const void *buf) {
  return flatbuffers::GetRoot<userpack::T_GET_USERLST_INFO_RQ>(buf);
}

inline bool VerifyT_GET_USERLST_INFO_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<userpack::T_GET_USERLST_INFO_RQ>(nullptr);
}

inline void FinishT_GET_USERLST_INFO_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<userpack::T_GET_USERLST_INFO_RQ> root) {
  fbb.Finish(root);
}

}  // namespace userpack

#endif  // FLATBUFFERS_GENERATED_FBGETUSERLSTINFORQ_USERPACK_H_
