// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBLOGINRS_SYSPACK_H_
#define FLATBUFFERS_GENERATED_FBLOGINRS_SYSPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace syspack {

struct T_LOGIN_RS;

struct T_LOGIN_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_SERVER_TIME = 6
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t server_time() const { return GetField<uint64_t>(VT_SERVER_TIME, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME) &&
           verifier.EndTable();
  }
};

struct T_LOGIN_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_LOGIN_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_server_time(uint64_t server_time) { fbb_.AddElement<uint64_t>(T_LOGIN_RS::VT_SERVER_TIME, server_time, 0); }
  T_LOGIN_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_LOGIN_RSBuilder &operator=(const T_LOGIN_RSBuilder &);
  flatbuffers::Offset<T_LOGIN_RS> Finish() {
    auto o = flatbuffers::Offset<T_LOGIN_RS>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_LOGIN_RS> CreateT_LOGIN_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t server_time = 0) {
  T_LOGIN_RSBuilder builder_(_fbb);
  builder_.add_server_time(server_time);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline const syspack::T_LOGIN_RS *GetT_LOGIN_RS(const void *buf) {
  return flatbuffers::GetRoot<syspack::T_LOGIN_RS>(buf);
}

inline bool VerifyT_LOGIN_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<syspack::T_LOGIN_RS>(nullptr);
}

inline void FinishT_LOGIN_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<syspack::T_LOGIN_RS> root) {
  fbb.Finish(root);
}

}  // namespace syspack

#endif  // FLATBUFFERS_GENERATED_FBLOGINRS_SYSPACK_H_
