// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBSMSVALIDRQ_SYSPACK_H_
#define FLATBUFFERS_GENERATED_FBSMSVALIDRQ_SYSPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace syspack {

struct T_SMS_VALID_RQ;

struct T_SMS_VALID_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_NATION_CODE = 6,
    VT_MOBILE = 8
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  int32_t nation_code() const { return GetField<int32_t>(VT_NATION_CODE, 0); }
  uint64_t mobile() const { return GetField<uint64_t>(VT_MOBILE, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<int32_t>(verifier, VT_NATION_CODE) &&
           VerifyField<uint64_t>(verifier, VT_MOBILE) &&
           verifier.EndTable();
  }
};

struct T_SMS_VALID_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_SMS_VALID_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_nation_code(int32_t nation_code) { fbb_.AddElement<int32_t>(T_SMS_VALID_RQ::VT_NATION_CODE, nation_code, 0); }
  void add_mobile(uint64_t mobile) { fbb_.AddElement<uint64_t>(T_SMS_VALID_RQ::VT_MOBILE, mobile, 0); }
  T_SMS_VALID_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_SMS_VALID_RQBuilder &operator=(const T_SMS_VALID_RQBuilder &);
  flatbuffers::Offset<T_SMS_VALID_RQ> Finish() {
    auto o = flatbuffers::Offset<T_SMS_VALID_RQ>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<T_SMS_VALID_RQ> CreateT_SMS_VALID_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    int32_t nation_code = 0,
    uint64_t mobile = 0) {
  T_SMS_VALID_RQBuilder builder_(_fbb);
  builder_.add_mobile(mobile);
  builder_.add_nation_code(nation_code);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline const syspack::T_SMS_VALID_RQ *GetT_SMS_VALID_RQ(const void *buf) {
  return flatbuffers::GetRoot<syspack::T_SMS_VALID_RQ>(buf);
}

inline bool VerifyT_SMS_VALID_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<syspack::T_SMS_VALID_RQ>(nullptr);
}

inline void FinishT_SMS_VALID_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<syspack::T_SMS_VALID_RQ> root) {
  fbb.Finish(root);
}

}  // namespace syspack

#endif  // FLATBUFFERS_GENERATED_FBSMSVALIDRQ_SYSPACK_H_
