// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBTIMESYNCRQ_SYSPACK_H_
#define FLATBUFFERS_GENERATED_FBTIMESYNCRQ_SYSPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace syspack {

struct T_TIME_SYNC_RQ;

struct T_TIME_SYNC_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           verifier.EndTable();
  }
};

struct T_TIME_SYNC_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_TIME_SYNC_RQ::VT_S_RQ_HEAD, s_rq_head); }
  T_TIME_SYNC_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_TIME_SYNC_RQBuilder &operator=(const T_TIME_SYNC_RQBuilder &);
  flatbuffers::Offset<T_TIME_SYNC_RQ> Finish() {
    auto o = flatbuffers::Offset<T_TIME_SYNC_RQ>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<T_TIME_SYNC_RQ> CreateT_TIME_SYNC_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0) {
  T_TIME_SYNC_RQBuilder builder_(_fbb);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline const syspack::T_TIME_SYNC_RQ *GetT_TIME_SYNC_RQ(const void *buf) {
  return flatbuffers::GetRoot<syspack::T_TIME_SYNC_RQ>(buf);
}

inline bool VerifyT_TIME_SYNC_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<syspack::T_TIME_SYNC_RQ>(nullptr);
}

inline void FinishT_TIME_SYNC_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<syspack::T_TIME_SYNC_RQ> root) {
  fbb.Finish(root);
}

}  // namespace syspack

#endif  // FLATBUFFERS_GENERATED_FBTIMESYNCRQ_SYSPACK_H_
