// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBFRIENDCLIENTADDRQ_FRIENDPACK_H_
#define FLATBUFFERS_GENERATED_FBFRIENDCLIENTADDRQ_FRIENDPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace friendpack {

struct T_FRIEND_CLIENT_ADD_RQ;

struct T_FRIEND_CLIENT_ADD_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_OWN_NICKNAME = 6,
    VT_PEER_USER_ID = 8,
    VT_SOURCE_TYPE = 10,
    VT_OP_MSG = 12
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  const flatbuffers::String *own_nickname() const { return GetPointer<const flatbuffers::String *>(VT_OWN_NICKNAME); }
  uint64_t peer_user_id() const { return GetField<uint64_t>(VT_PEER_USER_ID, 0); }
  int8_t source_type() const { return GetField<int8_t>(VT_SOURCE_TYPE, 0); }
  const flatbuffers::String *op_msg() const { return GetPointer<const flatbuffers::String *>(VT_OP_MSG); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_OWN_NICKNAME) &&
           verifier.Verify(own_nickname()) &&
           VerifyField<uint64_t>(verifier, VT_PEER_USER_ID) &&
           VerifyField<int8_t>(verifier, VT_SOURCE_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_OP_MSG) &&
           verifier.Verify(op_msg()) &&
           verifier.EndTable();
  }
};

struct T_FRIEND_CLIENT_ADD_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_FRIEND_CLIENT_ADD_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_own_nickname(flatbuffers::Offset<flatbuffers::String> own_nickname) { fbb_.AddOffset(T_FRIEND_CLIENT_ADD_RQ::VT_OWN_NICKNAME, own_nickname); }
  void add_peer_user_id(uint64_t peer_user_id) { fbb_.AddElement<uint64_t>(T_FRIEND_CLIENT_ADD_RQ::VT_PEER_USER_ID, peer_user_id, 0); }
  void add_source_type(int8_t source_type) { fbb_.AddElement<int8_t>(T_FRIEND_CLIENT_ADD_RQ::VT_SOURCE_TYPE, source_type, 0); }
  void add_op_msg(flatbuffers::Offset<flatbuffers::String> op_msg) { fbb_.AddOffset(T_FRIEND_CLIENT_ADD_RQ::VT_OP_MSG, op_msg); }
  T_FRIEND_CLIENT_ADD_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_FRIEND_CLIENT_ADD_RQBuilder &operator=(const T_FRIEND_CLIENT_ADD_RQBuilder &);
  flatbuffers::Offset<T_FRIEND_CLIENT_ADD_RQ> Finish() {
    auto o = flatbuffers::Offset<T_FRIEND_CLIENT_ADD_RQ>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<T_FRIEND_CLIENT_ADD_RQ> CreateT_FRIEND_CLIENT_ADD_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    flatbuffers::Offset<flatbuffers::String> own_nickname = 0,
    uint64_t peer_user_id = 0,
    int8_t source_type = 0,
    flatbuffers::Offset<flatbuffers::String> op_msg = 0) {
  T_FRIEND_CLIENT_ADD_RQBuilder builder_(_fbb);
  builder_.add_peer_user_id(peer_user_id);
  builder_.add_op_msg(op_msg);
  builder_.add_own_nickname(own_nickname);
  builder_.add_s_rq_head(s_rq_head);
  builder_.add_source_type(source_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_FRIEND_CLIENT_ADD_RQ> CreateT_FRIEND_CLIENT_ADD_RQDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    const char *own_nickname = nullptr,
    uint64_t peer_user_id = 0,
    int8_t source_type = 0,
    const char *op_msg = nullptr) {
  return CreateT_FRIEND_CLIENT_ADD_RQ(_fbb, s_rq_head, own_nickname ? _fbb.CreateString(own_nickname) : 0, peer_user_id, source_type, op_msg ? _fbb.CreateString(op_msg) : 0);
}

inline const friendpack::T_FRIEND_CLIENT_ADD_RQ *GetT_FRIEND_CLIENT_ADD_RQ(const void *buf) {
  return flatbuffers::GetRoot<friendpack::T_FRIEND_CLIENT_ADD_RQ>(buf);
}

inline bool VerifyT_FRIEND_CLIENT_ADD_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<friendpack::T_FRIEND_CLIENT_ADD_RQ>(nullptr);
}

inline void FinishT_FRIEND_CLIENT_ADD_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<friendpack::T_FRIEND_CLIENT_ADD_RQ> root) {
  fbb.Finish(root);
}

}  // namespace friendpack

#endif  // FLATBUFFERS_GENERATED_FBFRIENDCLIENTADDRQ_FRIENDPACK_H_
