// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBFRIENDCLIENTADDRS_FRIENDPACK_H_
#define FLATBUFFERS_GENERATED_FBFRIENDCLIENTADDRS_FRIENDPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace friendpack {

struct T_FRIEND_CLIENT_ADD_RS;

struct T_FRIEND_CLIENT_ADD_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_PEER_USER_ID = 6,
    VT_TOKEN = 8,
    VT_OP_MSG = 10
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t peer_user_id() const { return GetField<uint64_t>(VT_PEER_USER_ID, 0); }
  uint64_t token() const { return GetField<uint64_t>(VT_TOKEN, 0); }
  const flatbuffers::String *op_msg() const { return GetPointer<const flatbuffers::String *>(VT_OP_MSG); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_PEER_USER_ID) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_OP_MSG) &&
           verifier.Verify(op_msg()) &&
           verifier.EndTable();
  }
};

struct T_FRIEND_CLIENT_ADD_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_FRIEND_CLIENT_ADD_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_peer_user_id(uint64_t peer_user_id) { fbb_.AddElement<uint64_t>(T_FRIEND_CLIENT_ADD_RS::VT_PEER_USER_ID, peer_user_id, 0); }
  void add_token(uint64_t token) { fbb_.AddElement<uint64_t>(T_FRIEND_CLIENT_ADD_RS::VT_TOKEN, token, 0); }
  void add_op_msg(flatbuffers::Offset<flatbuffers::String> op_msg) { fbb_.AddOffset(T_FRIEND_CLIENT_ADD_RS::VT_OP_MSG, op_msg); }
  T_FRIEND_CLIENT_ADD_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_FRIEND_CLIENT_ADD_RSBuilder &operator=(const T_FRIEND_CLIENT_ADD_RSBuilder &);
  flatbuffers::Offset<T_FRIEND_CLIENT_ADD_RS> Finish() {
    auto o = flatbuffers::Offset<T_FRIEND_CLIENT_ADD_RS>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<T_FRIEND_CLIENT_ADD_RS> CreateT_FRIEND_CLIENT_ADD_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t peer_user_id = 0,
    uint64_t token = 0,
    flatbuffers::Offset<flatbuffers::String> op_msg = 0) {
  T_FRIEND_CLIENT_ADD_RSBuilder builder_(_fbb);
  builder_.add_token(token);
  builder_.add_peer_user_id(peer_user_id);
  builder_.add_op_msg(op_msg);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_FRIEND_CLIENT_ADD_RS> CreateT_FRIEND_CLIENT_ADD_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t peer_user_id = 0,
    uint64_t token = 0,
    const char *op_msg = nullptr) {
  return CreateT_FRIEND_CLIENT_ADD_RS(_fbb, s_rs_head, peer_user_id, token, op_msg ? _fbb.CreateString(op_msg) : 0);
}

inline const friendpack::T_FRIEND_CLIENT_ADD_RS *GetT_FRIEND_CLIENT_ADD_RS(const void *buf) {
  return flatbuffers::GetRoot<friendpack::T_FRIEND_CLIENT_ADD_RS>(buf);
}

inline bool VerifyT_FRIEND_CLIENT_ADD_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<friendpack::T_FRIEND_CLIENT_ADD_RS>(nullptr);
}

inline void FinishT_FRIEND_CLIENT_ADD_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<friendpack::T_FRIEND_CLIENT_ADD_RS> root) {
  fbb.Finish(root);
}

}  // namespace friendpack

#endif  // FLATBUFFERS_GENERATED_FBFRIENDCLIENTADDRS_FRIENDPACK_H_
