// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBFRIENDUPDATERQ_FRIENDPACK_H_
#define FLATBUFFERS_GENERATED_FBFRIENDUPDATERQ_FRIENDPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace friendpack {

struct T_FRIEND_UPDATE_RQ;

struct T_FRIEND_UPDATE_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_PEER_USER_ID = 6
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  uint64_t peer_user_id() const { return GetField<uint64_t>(VT_PEER_USER_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_PEER_USER_ID) &&
           verifier.EndTable();
  }
};

struct T_FRIEND_UPDATE_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_FRIEND_UPDATE_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_peer_user_id(uint64_t peer_user_id) { fbb_.AddElement<uint64_t>(T_FRIEND_UPDATE_RQ::VT_PEER_USER_ID, peer_user_id, 0); }
  T_FRIEND_UPDATE_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_FRIEND_UPDATE_RQBuilder &operator=(const T_FRIEND_UPDATE_RQBuilder &);
  flatbuffers::Offset<T_FRIEND_UPDATE_RQ> Finish() {
    auto o = flatbuffers::Offset<T_FRIEND_UPDATE_RQ>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_FRIEND_UPDATE_RQ> CreateT_FRIEND_UPDATE_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t peer_user_id = 0) {
  T_FRIEND_UPDATE_RQBuilder builder_(_fbb);
  builder_.add_peer_user_id(peer_user_id);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline const friendpack::T_FRIEND_UPDATE_RQ *GetT_FRIEND_UPDATE_RQ(const void *buf) {
  return flatbuffers::GetRoot<friendpack::T_FRIEND_UPDATE_RQ>(buf);
}

inline bool VerifyT_FRIEND_UPDATE_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<friendpack::T_FRIEND_UPDATE_RQ>(nullptr);
}

inline void FinishT_FRIEND_UPDATE_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<friendpack::T_FRIEND_UPDATE_RQ> root) {
  fbb.Finish(root);
}

}  // namespace friendpack

#endif  // FLATBUFFERS_GENERATED_FBFRIENDUPDATERQ_FRIENDPACK_H_
