// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBCLIENTGETOFFLINEMESSAGERQ_SCPACK_H_
#define FLATBUFFERS_GENERATED_FBCLIENTGETOFFLINEMESSAGERQ_SCPACK_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace scpack {

struct T_CHAT_GET_OFFLINE_MESSAGE_RQ;

struct T_CHAT_GET_OFFLINE_MESSAGE_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_NEXT_MESSAGE_ID = 6
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  uint64_t next_message_id() const { return GetField<uint64_t>(VT_NEXT_MESSAGE_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_NEXT_MESSAGE_ID) &&
           verifier.EndTable();
  }
};

struct T_CHAT_GET_OFFLINE_MESSAGE_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_CHAT_GET_OFFLINE_MESSAGE_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_next_message_id(uint64_t next_message_id) { fbb_.AddElement<uint64_t>(T_CHAT_GET_OFFLINE_MESSAGE_RQ::VT_NEXT_MESSAGE_ID, next_message_id, 0); }
  T_CHAT_GET_OFFLINE_MESSAGE_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_CHAT_GET_OFFLINE_MESSAGE_RQBuilder &operator=(const T_CHAT_GET_OFFLINE_MESSAGE_RQBuilder &);
  flatbuffers::Offset<T_CHAT_GET_OFFLINE_MESSAGE_RQ> Finish() {
    auto o = flatbuffers::Offset<T_CHAT_GET_OFFLINE_MESSAGE_RQ>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_CHAT_GET_OFFLINE_MESSAGE_RQ> CreateT_CHAT_GET_OFFLINE_MESSAGE_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t next_message_id = 0) {
  T_CHAT_GET_OFFLINE_MESSAGE_RQBuilder builder_(_fbb);
  builder_.add_next_message_id(next_message_id);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline const scpack::T_CHAT_GET_OFFLINE_MESSAGE_RQ *GetT_CHAT_GET_OFFLINE_MESSAGE_RQ(const void *buf) {
  return flatbuffers::GetRoot<scpack::T_CHAT_GET_OFFLINE_MESSAGE_RQ>(buf);
}

inline bool VerifyT_CHAT_GET_OFFLINE_MESSAGE_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<scpack::T_CHAT_GET_OFFLINE_MESSAGE_RQ>(nullptr);
}

inline void FinishT_CHAT_GET_OFFLINE_MESSAGE_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<scpack::T_CHAT_GET_OFFLINE_MESSAGE_RQ> root) {
  fbb.Finish(root);
}

}  // namespace scpack

#endif  // FLATBUFFERS_GENERATED_FBCLIENTGETOFFLINEMESSAGERQ_SCPACK_H_
